### ISSUE TITLE
Uncaught TypeError: util.inherits is not a function

### ISSUE THREAD

**Issue by danielbentov** [algolia/react-instantsearch#173]
Trying to use the lib.

```js
import React, {Component} from 'react'
import classnames from 'classnames'
import {bindActionCreators} from 'redux'
import {connect} from 'react-redux'
import Autosuggest from 'react-autosuggest';
import {mouseTrap} from 'react-mousetrap';
import BZModal from 'BZModal';
import _ from 'underscore';
import {
    Configure,
    InstantSearch,
    Index,
    Highlight,
    SearchBox
} from 'react-instantsearch/dom';
import {
     connectHits,
     connectAutoComplete
 } from 'react-instantsearch/connectors';
import PubSub from '../PubSub';
```

![image](https://user-images.githubusercontent.com/8301213/28360914-9a21b3d4-6c7f-11e7-8133-a730be17a555.png)

But getting this error on the client. 
Happens on Chrome.
We are using webpack 1.15.0
Npm 5.0.2
React 15.6.1
Node 6.9.2

![image](https://user-images.githubusercontent.com/8301213/28360929-a719c28e-6c7f-11e7-8420-c4df8807967c.png)

![image](https://user-images.githubusercontent.com/8301213/28360684-df2be9fa-6c7e-11e7-9638-c41551a474a1.png)

**Comment by mthuret** [comment]
Hi @danielbentov, could you give us a small repo reproducing the issue you're facing as it would be easier for us to understand. 

Thanks in advance!

**Comment by danielbentov** [comment]
Hi @mthuret,
I can not create a repo that will mimic our product (we have 5 years of code there).
I can tell you that it seems that working with node 6.11.0 and Webpack caused the issue.
You are using util.inherits in your code.

https://github.com/webpack/webpack/issues/1019
https://github.com/defunctzombie/node-util/issues/17

**Comment by mthuret** [comment]
I didn't succeed reproducing the issue based on webpack 2 and node 6.11.0. I'm also confused because you indicate that you're using webpack 1.15.0 and node 6.9.2? 

@bobylito, as it seems to be related to helper, did you already encounter this issue?

**Comment by mthuret** [comment]
Also @danielbentov, can you indicate which version of react instantsearch you are using. And if you're not using 4.1.0-beta.2, can you try with it?

**Comment by danielbentov** [comment]
Still happening with 4.1.0-beta.2

![image](https://user-images.githubusercontent.com/8301213/28529742-001fbd5c-709a-11e7-9828-67ca29f6c035.png)

**Comment by danielbentov** [comment]
@mthuret I fixed it with the following code:
node-libs-browser is using inherits 2.0.1.
It's a Webpack bug.
`
npm i util@0.10.3 --save

Adding to webpack
resolve: {
  alias: {
    util$: path.resolve(__dirname, 'node_modules/util')`

**Comment by mthuret** [comment]
@danielbentov awesome! I'm closing this, then.

Don't hesitate to reach to us again for any questions about the lib :)

**Comment by VapiSoft** [comment]
I still get the same error, it didn't help.

**Comment by Haroenv** [comment]
@VapiSoft please make a new issue with reproduction

**Comment by markpradhan** [comment]
```js
module.exports = {
  resolve: {
    mainFields: ['browser', 'module', 'main']
  }
};
```
Adding this to the webpack config solved it for me.

**Comment by Haroenv** [comment]
We haven't been using `util` for a while now, which version of React InstantSearch did you have this issue with @markpradhan ?

**Comment by markpradhan** [comment]
Ah my bad, i found this thread looking for an answer, though it would help if people still had this issue as it looks very similar to whatever i was experiencing (issue in react-pdf). I am not using instant search at all. Sorry for pinging you guys!
