### PR TITLE
Fix Virtual Widget doc

### PR DESCRIPTION
**Pull request by babgyy**
Fixed import of connectMenu.

**Summary**
Previous import was not failing, however the below example was raising following mounting-time error: 
```Uncaught TypeError: Object(...) is not a function```

**Result**
I have found at least two ways to import connectMenu in the repo's source : 
- react-instantsearch/connectors
- react-instantsearch-core

Both seem to work with react-instantsearch v5.3.2.

### CODE REVIEW

**Comment by Haroenv** [comment]
The way written in the documentation should work though 🤔 https://unpkg.com/react-instantsearch-dom@5.3.2/dist/es/index.js, as you can see, all of the connectors are exported. Which version are you using that doesn't export it?

**Comment by samouss** [comment]
The import of the package recently change. The sample from the documentation should work. You can find more information about the migration [inside the documentation](https://community.algolia.com/react-instantsearch/guide/Migration_guide_package_import.html). Here is [an example](https://codesandbox.io/s/wq6x33jw58) that import `connectMenu` from the `react-instantsearch-dom` without any issue. Could you provide an example with an import that failed? Here is [a template](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch) to avoid the boilerplate part.
